package entities;

// default package
// Generated 26 Oct 2021, 01:37:27 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", catalog = "empresa")
public class Departamento implements java.io.Serializable {

	private int codigo;
	private int codResponsable;
	private String nombre;

	public Departamento() {
	}

	public Departamento(int codigo, int codResponsable, String nombre) {
		this.codigo = codigo;
		this.codResponsable = codResponsable;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "cod_responsable", nullable = false)
	public int getCodResponsable() {
		return this.codResponsable;
	}

	public void setCodResponsable(int codResponsable) {
		this.codResponsable = codResponsable;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
